### ISSUE TITLE
`vec4` + `vec3` classes, with SIMD intrinsics support

### ISSUE THREAD

**Issue by wermos** [wermos/Rendera#13]
The task is to create a `vec4` class, which will be a vector with 4 elements, with the relevant functionality (like adding, subtracting, multiplication and division by a scalar).

Use the `xsimd` submodule for SIMD intrinsics to speed up the math operations, and provide reasonable constructors.

Make the `vec3` class by inherting from `vec4`, and supply a cross product function for the 3 dimensional vectors.

You might find [this link](https://geometrian.com/programming/tutorials/cross-product/index.php) on how you can use SIMD intrinsics for computing the cross product of two 3D vectors interesting.

Assignee: @prateekgargX

**Comment by prateekgargX** [comment]
Completed by #35.
