### ISSUE TITLE
Adding Cubes

### ISSUE THREAD

**Issue by divyanshtiwari237** [wermos/Rendera#21]
Currently, the RayTracer only supports sphere objects. Implement cubes into the project.

This will involve the following:
1.) Implementing a Cube class that stores the dimensions and other necessary features.
2.) Implement ray-box intersections which are necessary to render the cube onto the image.

References:
1.) [Scratchapixel](https://www.scratchapixel.com/lessons/3d-basic-rendering/minimal-ray-tracer-rendering-simple-shapes/ray-box-intersection)
2.)The RayTracer Challenge

Assignee: @KartikDhawaniya

**Comment by wermos** [comment]
Closed as completed by #29.
